AllCops:
  NewCops: enable
  Exclude:
    - "vendor/bundle/**/*"
    - "vendor/*"
    - "bin/**/*"
    - "db/**/*"
    - "config/**/*"
    - "node_modules/**/*"
    - "script/**/*"
    - "support/**/*"
    - "tmp/**/*"
    - "test/**/*"
    - "db/seeds.rb"
    - "db/schema.rb"
    - "db/migrate/*"
    - "app/helpers/helpers.rb"
    - "bin/bundle"
    - "config/initializers/simple_form.rb"
Style/ConditionalAssignment:
  Enabled: false
Style/StringLiterals:
  Enabled: false
Style/RedundantReturn:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/WordArray:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Style/MutableConstant:
  Enabled: false
Style/SignalException:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Style/MissingRespondToMissing:
  Enabled: false
Lint/MissingSuper:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Layout/LineLength:
  Max: 120
  Exclude:
    - "config/initializers/devise.rb"
Style/EmptyMethod:
  Enabled: false
Bundler/OrderedGems:
  Enabled: false
Metrics/MethodLength:
  Max: 15
Metrics/BlockLength:
  Max: 45
  Exclude:
    - "spec/*/*"
    - "spec/factories.rb"
